// Generated by https://quicktype.io

export interface Event {
    _id?:                     string;
    category?:                string;
    iva?:                     boolean;
    valueIva?:                number;
    secretLocation?:          boolean;
    discountDisability?:      boolean;
    isAllPublic?:             boolean;
    discountChildren?:        boolean;
    preSales?:                boolean;
    comment?:                 string;
    available?:               string;
    isDelete?:                boolean;
    payments?:                null;
    hasCapacity?:             boolean;
    maximunTickets?:          number;
    nameEvent?:               string;
    description?:             string;
    city?:                    City;
    place?:                   string;
    date?:                    string;
    startTime?:               string;
    endTime?:                 string;
    lat?:                     string;
    lng?:                     string;
    ageChildren?:             number;
    percentageDisability?:    number;
    percentageChildren?:      number;
    existRequirements?:       boolean;
    requirementsDescription?: string;
    hasParking?:              boolean;
    parkingNumber?:           null;
    openingHours?:            string;
    img?:                     string;
    isFree?:                  boolean;
    organizer?:               string;
    sponsors?:                any[];
    timeName?:                any[];
}

export interface City {
    _id:         string;
    description: string;
    province?:    string;
}
