export interface Location {
    _id:         string;
    province?:    Location;
    descripcion: string;
}

// Generated by https://quicktype.io

export interface LocatyWithPhase {
    _id?:            string;
    description?:    string;
    typeNumbering?:  null;
    amount?:         string;
    priceNoIva?:     string;
    priceIva?:       string;
    stock?:          string;
    event?:          string;
    listSubscriber?: Array<any[]>;
    phases?:         Phase[];
}

export interface Phase {
    _id?:             string;
    status?:          boolean;
    public?:          string[];
    type?:            string;
    position?:        number;
    name?:            string;
    priceWithVAT?:    string;
    priceWithoutVAT?: string;
    stock?:           number;
    typePublic?:      string;
    locality?:        string;
    log?:             string;
    __v?:             number;
}
